# Baked / SD autoconnect list (priority high → low)
# Paths checked at boot:
#   1) /sdcard/conf/auto_connect.txt
#   2) embedded main/autoconnect.conf (linked as binary if present)
#note to self DO NOT PUSH TO GITHUB THIS IS A PRIVATE PASSWORD!!!
wifi_autoconnect:

1: ssid: "YOUR_SSID" pass: "YOUR_PASSWORD"
2: ssid: "backup-ap" pass: "backup-pass"
wifi_autoconnect_end

bluetooth_autoconnect:
1: name: "MyBT" pass: "0000"
bluetooth_autoconnect_end
